# Generated by Django 5.2.7 on 2025-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=120)),
                ('start_period', models.DateField()),
                ('end_period', models.DateField()),
                ('contributions', models.JSONField(help_text='list_of_contributions')),
                ('project_sample_media_path', models.TextField(blank=True, help_text='Path or filename of related media', null=True)),
                ('project_sample_url', models.URLField(blank=True, help_text='Optional link to project', null=True)),
            ],
        ),
    ]
