# Generated by Django 5.2.7 on 2025-10-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_remove_experience_contributions_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='project_sample_media_path',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='project_sample_url',
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_period',
            field=models.DateField(help_text='end date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_period',
            field=models.DateField(help_text='joined date'),
        ),
    ]
